package sh.pcx.packmerger.discovery;

import java.io.File;
import java.util.List;

/**
 * Describes how to locate the resource pack <em>generated by another installed
 * plugin</em> (Oraxen, Nexo, ItemsAdder, ModelEngine, …) so PackMerger can pull
 * it into the merge automatically.
 *
 * <p>Adapters are data-driven: each is just an alias, the Bukkit plugin name used
 * for detection, and an ordered list of candidate paths (relative to the server's
 * {@code plugins/} folder) where that plugin writes its pack. The first existing
 * candidate wins; a candidate may be a {@code .zip} or a pack directory.</p>
 *
 * <p>Output paths differ between plugin versions and can change, so every adapter's
 * path is overridable via {@code plugin-packs.sources.<alias>.path} in config — the
 * built-in candidates are best-effort defaults, not a hard contract.</p>
 *
 * <p>The staged pack flows through the normal merge pipeline by its {@code alias},
 * so it is <em>deep-merged</em> by the format-aware strategies — not merely
 * file-overwritten by priority.</p>
 */
public final class PluginPackAdapter {

    private final String alias;
    private final String pluginName;
    private final List<String> candidatePaths;

    public PluginPackAdapter(String alias, String pluginName, List<String> candidatePaths) {
        this.alias = alias;
        this.pluginName = pluginName;
        this.candidatePaths = List.copyOf(candidatePaths);
    }

    /** Staging filename and the name used to reference this pack in {@code priority:}. */
    public String alias() { return alias; }

    /** Bukkit plugin name used for presence detection (e.g. {@code "Oraxen"}). */
    public String pluginName() { return pluginName; }

    /** Default candidate source paths, relative to {@code plugins/}, in priority order. */
    public List<String> candidatePaths() { return candidatePaths; }

    /**
     * Resolves this plugin's generated-pack source.
     *
     * @param pluginsFolder the server's {@code plugins/} directory
     * @param overridePath  an operator-supplied path (absolute, or relative to
     *                      {@code plugins/}); {@code null}/blank to use defaults
     * @return the existing source {@link File} (a {@code .zip} or a directory), or
     *         {@code null} if nothing was found
     */
    public File resolveSource(File pluginsFolder, String overridePath) {
        if (overridePath != null && !overridePath.isBlank()) {
            File f = new File(overridePath);
            if (!f.isAbsolute()) f = new File(pluginsFolder, overridePath);
            return f.exists() ? f : null;
        }
        for (String rel : candidatePaths) {
            File f = new File(pluginsFolder, rel);
            if (f.exists()) return f;
        }
        return null;
    }

    /**
     * The built-in adapter registry, highest-value plugins first. Candidate paths
     * are best-effort defaults; operators override per-plugin in config when a
     * plugin's layout differs.
     */
    public static List<PluginPackAdapter> builtIns() {
        return List.of(
                new PluginPackAdapter("oraxen", "Oraxen",
                        List.of("Oraxen/pack/pack.zip", "Oraxen/pack")),
                new PluginPackAdapter("nexo", "Nexo",
                        List.of("Nexo/pack/pack.zip", "Nexo/pack/assets")),
                new PluginPackAdapter("itemsadder", "ItemsAdder",
                        List.of("ItemsAdder/output/generated.zip", "ItemsAdder/contents")),
                new PluginPackAdapter("modelengine", "ModelEngine",
                        List.of("ModelEngine/resource pack.zip", "ModelEngine/resource pack")),
                new PluginPackAdapter("elitemobs", "EliteMobs",
                        List.of("EliteMobs/resourcepack.zip", "EliteMobs/resourcepackv2")),
                new PluginPackAdapter("freeminecraftmodels", "FreeMinecraftModels",
                        List.of("FreeMinecraftModels/resourcepack.zip", "FreeMinecraftModels/resource_pack"))
        );
    }
}
