package sh.pcx.packmerger.discovery;

import org.bukkit.Bukkit;
import sh.pcx.packmerger.PackMergerBootstrap;
import sh.pcx.packmerger.PluginLogger;
import sh.pcx.packmerger.config.ConfigManager;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Discovers resource packs generated by other installed plugins and stages each
 * into {@code packs/.plugin-packs/<alias>.zip} so the existing merge pipeline
 * consumes them by alias — exactly like {@link sh.pcx.packmerger.remote.RemotePackManager}
 * stages remote packs into {@code packs/.remote-cache/}.
 *
 * <p>{@link #stageAll()} is re-run before every merge so a later
 * {@code /oraxen reload} (or any plugin re-emitting its pack) is picked up by the
 * next {@code /pm merge}. Staged packs flow through the format-aware deep-merge
 * strategies; we never bypass them with whole-file overwrite.</p>
 */
public class PluginPackManager {

    /** Sub-directory of {@code packs/} where detected plugin packs are staged. */
    public static final String STAGE_DIR = ".plugin-packs";

    private final PackMergerBootstrap plugin;
    private final PluginLogger logger;
    private final File stageDir;

    /** Detected-but-not-merged advisory for ops, or {@code null} when all good. */
    private volatile String advisory;

    public PluginPackManager(PackMergerBootstrap plugin) {
        this.plugin = plugin;
        this.logger = plugin.getPluginLogger();
        this.stageDir = new File(plugin.getPacksFolder(), STAGE_DIR);
    }

    /** @return {@code packs/.plugin-packs/} — created on demand */
    public File stageDir() {
        if (!stageDir.exists()) stageDir.mkdirs();
        return stageDir;
    }

    /** The server's {@code plugins/} directory (parent of {@code plugins/PackMerger/}). */
    private File pluginsFolder() {
        return plugin.getLoader().getDataFolder().getParentFile();
    }

    /**
     * Stages every enabled, detected plugin's current generated pack into
     * {@code packs/.plugin-packs/}. Safe to call before each merge.
     *
     * @return the number of packs staged this pass
     */
    public int stageAll() {
        ConfigManager cfg = plugin.getConfigManager();
        if (!cfg.isPluginPacksEnabled()) {
            advisory = null;
            return 0;
        }

        File plugins = pluginsFolder();
        int staged = 0;
        List<String> notMerged = new ArrayList<>();

        for (PluginPackAdapter adapter : PluginPackAdapter.builtIns()) {
            boolean present = Bukkit.getPluginManager().getPlugin(adapter.pluginName()) != null;
            if (!present) continue;

            ConfigManager.PluginPackSetting setting = cfg.getPluginPackSetting(adapter.alias());
            boolean enabled = setting == null || setting.enabled();
            if (!enabled) {
                notMerged.add(adapter.pluginName() + " (disabled in config)");
                continue;
            }

            String override = setting == null ? null : setting.path();
            File source = adapter.resolveSource(plugins, override);
            if (source == null) {
                notMerged.add(adapter.pluginName() + " (no generated pack found — build its pack, "
                        + "or set plugin-packs.sources." + adapter.alias() + ".path)");
                continue;
            }

            try {
                stageOne(adapter.alias(), source);
                staged++;
                logger.info("[plugin-packs] staged " + adapter.pluginName() + " ← " + source.getName());
            } catch (IOException e) {
                notMerged.add(adapter.pluginName() + " (staging failed: " + e.getMessage() + ")");
                logger.warning("[plugin-packs] failed to stage " + adapter.pluginName() + ": " + e.getMessage());
            }
        }

        advisory = notMerged.isEmpty() ? null
                : "PackMerger: pack-generating plugins installed but not merged → "
                        + String.join("; ", notMerged);
        if (advisory != null) logger.warning("[plugin-packs] " + advisory);
        return staged;
    }

    /** Stages a single source (zip copied as-is; directory zipped) via atomic rename. */
    private void stageOne(String alias, File source) throws IOException {
        File part = new File(stageDir(), alias + ".zip.part");
        File dest = new File(stageDir(), alias + ".zip");
        if (source.isDirectory()) {
            zipDirectory(source, part);
        } else {
            Files.copy(source.toPath(), part.toPath(), StandardCopyOption.REPLACE_EXISTING);
        }
        Files.move(part.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);
    }

    /**
     * Zips the contents of {@code dir} (entries relative to {@code dir}, forward
     * slashes) into {@code destZip}. Package-private + static for testing.
     */
    static void zipDirectory(File dir, File destZip) throws IOException {
        Path base = dir.toPath();
        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(destZip.toPath()));
             Stream<Path> walk = Files.walk(base)) {
            List<Path> files = walk.filter(Files::isRegularFile).sorted().toList();
            for (Path p : files) {
                String entry = base.relativize(p).toString().replace(File.separatorChar, '/');
                zos.putNextEntry(new ZipEntry(entry));
                Files.copy(p, zos);
                zos.closeEntry();
            }
        }
    }

    /**
     * @return a one-line advisory naming installed pack-generating plugins that
     *         are <em>not</em> being merged (disabled, missing output, or staging
     *         failure), or {@code null} when everything detected is merged. Populated
     *         by {@link #stageAll()}.
     */
    public String getAdvisoryMessageOrNull() {
        return advisory;
    }
}
